# Generated by Django 5.2.16 on 2026-07-30 23:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('current_step', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='flights.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Journeys',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TravelChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('is_packed', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('documents', 'Documents'), ('electronics', 'Electronics'), ('medicine', 'Medicine'), ('clothing', 'Clothing'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='journey.journey')),
            ],
            options={
                'verbose_name_plural': 'Travel Checklist Items',
                'ordering': ('category', 'item_name'),
            },
        ),
        migrations.CreateModel(
            name='JourneyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('leave_home', 'Leave Home'), ('arrive_airport', 'Arrive at Airport'), ('parking', 'Parking'), ('check_in', 'Check-in'), ('bag_drop', 'Bag Drop'), ('passport_control', 'Passport Control'), ('security', 'Security'), ('duty_free', 'Duty Free'), ('gate', 'Gate'), ('boarding', 'Boarding'), ('seat', 'Seat')], max_length=30)),
                ('order', models.PositiveIntegerField()),
                ('estimated_minutes', models.PositiveIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, default='')),
                ('voice_guide_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='journey.journey')),
            ],
            options={
                'ordering': ('order',),
                'unique_together': {('journey', 'order')},
            },
        ),
    ]
