JFK_AIRPORT_DATA = {
    "code": "JFK",
    "name": "John F. Kennedy International Airport",
    "location": {
        "city": "New York",
        "state": "New York",
        "country": "USA",
        "coordinates": {"lat": 40.6413, "lng": -73.7781},
    },
    "terminals": [
        {
            "number": 1,
            "name": "Terminal 1",
            "description": "International terminal serving Air France, Lufthansa, Korean Air, Japan Airlines, and others",
            "coordinates": {"lat": 40.6450, "lng": -73.7800},
        },
        {
            "number": 2,
            "name": "Terminal 2",
            "description": "Delta Air Lines domestic terminal",
            "coordinates": {"lat": 40.6430, "lng": -73.7760},
        },
        {
            "number": 3,
            "name": "Terminal 3",
            "description": "Delta Air Lines international terminal (formerly Pan Am Worldport)",
            "coordinates": {"lat": 40.6410, "lng": -73.7740},
        },
        {
            "number": 4,
            "name": "Terminal 4",
            "description": "Main international terminal serving Emirates, Singapore Airlines, Virgin Atlantic, and many more",
            "coordinates": {"lat": 40.6420, "lng": -73.7720},
        },
        {
            "number": 5,
            "name": "Terminal 5",
            "description": "JetBlue terminal (formerly TWA Flight Center)",
            "coordinates": {"lat": 40.6455, "lng": -73.7680},
        },
        {
            "number": 6,
            "name": "Terminal 6",
            "description": "Former JetBlue terminal (currently under renovation)",
            "coordinates": {"lat": 40.6460, "lng": -73.7660},
        },
        {
            "number": 7,
            "name": "Terminal 7",
            "description": "International terminal serving British Airways, Icelandair, and others",
            "coordinates": {"lat": 40.6470, "lng": -73.7650},
        },
        {
            "number": 8,
            "name": "Terminal 8",
            "description": "American Airlines hub terminal (largest terminal at JFK)",
            "coordinates": {"lat": 40.6480, "lng": -73.7620},
        },
    ],
    "gates": {
        "Terminal 1": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11"],
        "Terminal 2": ["12", "13", "14", "15", "16", "17", "18", "19", "20", "21"],
        "Terminal 3": ["C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "C9", "C10"],
        "Terminal 4": ["A2", "A3", "A5", "A6", "A7", "B20", "B21", "B22", "B23", "B24", "B25", "B26", "B27", "B28", "B29", "B30", "B31", "B32", "B33", "B34", "B35", "B36", "B37", "B38", "B39", "B40", "B41", "B42", "B43", "B44"],
        "Terminal 5": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
        "Terminal 6": ["1", "2", "3", "4", "5"],
        "Terminal 7": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"],
        "Terminal 8": ["12", "14", "15", "16", "17", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66"],
    },
    "amenities": [
        {"id": "amen_01", "name": "Piquillo", "type": "restaurant", "terminal": "Terminal 1", "gate_area": "Near Gate 1", "description": "Spanish tapas and wine bar with a cozy atmosphere", "coordinates": {"lat": 40.6451, "lng": -73.7801, "floor": 2}},
        {"id": "amen_02", "name": "Starbucks", "type": "restaurant", "terminal": "Terminal 1", "gate_area": "Near Gate 3", "description": "Coffee and quick bites", "coordinates": {"lat": 40.6452, "lng": -73.7802, "floor": 2}},
        {"id": "amen_03", "name": "McDonald's", "type": "restaurant", "terminal": "Terminal 1", "gate_area": "Food Court", "description": "24/7 fast food classics", "coordinates": {"lat": 40.6453, "lng": -73.7803, "floor": 1}},
        {"id": "amen_04", "name": "Shake Shack", "type": "restaurant", "terminal": "Terminal 2", "gate_area": "Near Gate 15", "description": "Famous burgers, shakes, and fries", "coordinates": {"lat": 40.6431, "lng": -73.7761, "floor": 2}},
        {"id": "amen_05", "name": "Palm Bar", "type": "restaurant", "terminal": "Terminal 2", "gate_area": "Near Gate 18", "description": "Full bar and American fare", "coordinates": {"lat": 40.6432, "lng": -73.7762, "floor": 2}},
        {"id": "amen_06", "name": "Uptown Brasserie", "type": "restaurant", "terminal": "Terminal 4", "gate_area": "Near B22", "description": "Sit-down American brasserie with full bar", "coordinates": {"lat": 40.6421, "lng": -73.7721, "floor": 3}},
        {"id": "amen_07", "name": "Blue Point Brewery", "type": "restaurant", "terminal": "Terminal 4", "gate_area": "Near B31", "description": "Craft beer and fresh seafood", "coordinates": {"lat": 40.6422, "lng": -73.7722, "floor": 3}},
        {"id": "amen_08", "name": "Berkshire Farms Market", "type": "restaurant", "terminal": "Terminal 4", "gate_area": "Near A2", "description": "Healthy bowls, salads, and smoothies", "coordinates": {"lat": 40.6423, "lng": -73.7723, "floor": 2}},
        {"id": "amen_09", "name": "TWA Hotel Restaurant", "type": "restaurant", "terminal": "Terminal 5", "gate_area": "TWA Hotel", "description": "Retro dining experience in the iconic TWA Flight Center", "coordinates": {"lat": 40.6456, "lng": -73.7681, "floor": 1}},
        {"id": "amen_10", "name": "AeroNuova", "type": "restaurant", "terminal": "Terminal 5", "gate_area": "Near Gate 6", "description": "Italian cuisine with a modern twist", "coordinates": {"lat": 40.6457, "lng": -73.7682, "floor": 2}},
        {"id": "amen_11", "name": "Starbucks", "type": "restaurant", "terminal": "Terminal 5", "gate_area": "Near Gate 4", "description": "Coffee and snacks", "coordinates": {"lat": 40.6458, "lng": -73.7683, "floor": 2}},
        {"id": "amen_12", "name": "InMotion", "type": "shop", "terminal": "Terminal 1", "gate_area": "Near Gate 2", "description": "Headphones, chargers, and travel electronics", "coordinates": {"lat": 40.6454, "lng": -73.7804, "floor": 2}},
        {"id": "amen_13", "name": "Duty Free Americas", "type": "shop", "terminal": "Terminal 1", "gate_area": "Near Security", "description": "Cosmetics, liquor, fragrances, and watches", "coordinates": {"lat": 40.6455, "lng": -73.7805, "floor": 2}},
        {"id": "amen_14", "name": "Coach", "type": "shop", "terminal": "Terminal 4", "gate_area": "Near B25", "description": "Luxury handbags, accessories, and leather goods", "coordinates": {"lat": 40.6424, "lng": -73.7724, "floor": 3}},
        {"id": "amen_15", "name": "Michael Kors", "type": "shop", "terminal": "Terminal 4", "gate_area": "Near B30", "description": "Designer fashion, watches, and accessories", "coordinates": {"lat": 40.6425, "lng": -73.7725, "floor": 3}},
        {"id": "amen_16", "name": "Swarovski", "type": "shop", "terminal": "Terminal 4", "gate_area": "Near B28", "description": "Crystal jewelry, figurines, and home decor", "coordinates": {"lat": 40.6426, "lng": -73.7726, "floor": 3}},
        {"id": "amen_17", "name": "Burberry", "type": "shop", "terminal": "Terminal 5", "gate_area": "Near Gate 8", "description": "British luxury fashion house", "coordinates": {"lat": 40.6459, "lng": -73.7684, "floor": 2}},
        {"id": "amen_18", "name": "Tumi", "type": "shop", "terminal": "Terminal 5", "gate_area": "Near Gate 5", "description": "Premium luggage, backpacks, and travel bags", "coordinates": {"lat": 40.6460, "lng": -73.7685, "floor": 2}},
        {"id": "amen_19", "name": "MAC Cosmetics", "type": "shop", "terminal": "Terminal 4", "gate_area": "Near B26", "description": "Professional makeup and beauty products", "coordinates": {"lat": 40.6427, "lng": -73.7727, "floor": 3}},
        {"id": "amen_20", "name": "Best Buy Express", "type": "shop", "terminal": "Terminal 4", "gate_area": "Near B35", "description": "Electronics, accessories, and travel gadgets", "coordinates": {"lat": 40.6428, "lng": -73.7728, "floor": 2}},
        {"id": "amen_21", "name": "New York Minute", "type": "shop", "terminal": "Terminal 4", "gate_area": "Near A5", "description": "NYC souvenirs, t-shirts, hats, and gifts", "coordinates": {"lat": 40.6429, "lng": -73.7729, "floor": 2}},
        {"id": "amen_22", "name": "Duty Free Americas", "type": "shop", "terminal": "Terminal 4", "gate_area": "Near Security", "description": "Cosmetics, liquor, fragrances, and watches", "coordinates": {"lat": 40.6430, "lng": -73.7730, "floor": 3}},
        {"id": "amen_23", "name": "Delta Sky Club", "type": "lounge", "terminal": "Terminal 2", "gate_area": "Near Gate 14", "description": "Delta and SkyTeam premium lounge with bar, food, and showers", "coordinates": {"lat": 40.6433, "lng": -73.7763, "floor": 3}},
        {"id": "amen_24", "name": "Delta Sky Club", "type": "lounge", "terminal": "Terminal 4", "gate_area": "Near B36", "description": "Delta and SkyTeam premium lounge with runway views", "coordinates": {"lat": 40.6431, "lng": -73.7731, "floor": 3}},
        {"id": "amen_25", "name": "American Admirals Club", "type": "lounge", "terminal": "Terminal 8", "gate_area": "Near Gate 42", "description": "American Airlines and oneworld lounge", "coordinates": {"lat": 40.6481, "lng": -73.7621, "floor": 3}},
        {"id": "amen_26", "name": "United Club", "type": "lounge", "terminal": "Terminal 7", "gate_area": "Near Gate 5", "description": "United Airlines and Star Alliance lounge", "coordinates": {"lat": 40.6471, "lng": -73.7651, "floor": 2}},
        {"id": "amen_27", "name": "Air France/KLM Lounge", "type": "lounge", "terminal": "Terminal 1", "gate_area": "Near Gate 6", "description": "SkyTeam premium lounge with French flair", "coordinates": {"lat": 40.6456, "lng": -73.7806, "floor": 3}},
        {"id": "amen_28", "name": "British Airways Galleries", "type": "lounge", "terminal": "Terminal 7", "gate_area": "Near Gate 8", "description": "British Airways and oneworld premium lounge", "coordinates": {"lat": 40.6472, "lng": -73.7652, "floor": 2}},
        {"id": "amen_29", "name": "Centurion Lounge", "type": "lounge", "terminal": "Terminal 4", "gate_area": "Near B25", "description": "American Express Centurion lounge with premium dining", "coordinates": {"lat": 40.6432, "lng": -73.7732, "floor": 4}},
        {"id": "amen_30", "name": "Chase Sapphire Lounge", "type": "lounge", "terminal": "Terminal 5", "gate_area": "Near Gate 3", "description": "Chase Sapphire Reserve cardholder lounge", "coordinates": {"lat": 40.6461, "lng": -73.7686, "floor": 2}},
        {"id": "amen_31", "name": "The Club JFK", "type": "lounge", "terminal": "Terminal 4", "gate_area": "Near B27", "description": "Priority Pass and DragonPass accessible lounge", "coordinates": {"lat": 40.6433, "lng": -73.7733, "floor": 3}},
        {"id": "amen_32", "name": "Restroom Area A", "type": "restroom", "terminal": "Terminal 1", "gate_area": "Near Gate 1", "description": "Restrooms with family/changing facilities", "coordinates": {"lat": 40.6457, "lng": -73.7807, "floor": 2}},
        {"id": "amen_33", "name": "Restroom Area B", "type": "restroom", "terminal": "Terminal 4", "gate_area": "Near B20", "description": "Restrooms with family/changing facilities", "coordinates": {"lat": 40.6434, "lng": -73.7734, "floor": 2}},
        {"id": "amen_34", "name": "Restroom Area C", "type": "restroom", "terminal": "Terminal 5", "gate_area": "Near Gate 2", "description": "Restrooms with family/changing facilities", "coordinates": {"lat": 40.6462, "lng": -73.7687, "floor": 2}},
        {"id": "amen_35", "name": "Restroom Area D", "type": "restroom", "terminal": "Terminal 8", "gate_area": "Near Gate 30", "description": "Restrooms with family/changing facilities", "coordinates": {"lat": 40.6482, "lng": -73.7622, "floor": 2}},
        {"id": "amen_36", "name": "Charging Station - Concourse A", "type": "charging", "terminal": "Terminal 4", "gate_area": "Near B22", "description": "Blue charging towers with USB and AC outlets", "coordinates": {"lat": 40.6435, "lng": -73.7735, "floor": 2}},
        {"id": "amen_37", "name": "Charging Station - Concourse B", "type": "charging", "terminal": "Terminal 5", "gate_area": "Near Gate 7", "description": "Seats with built-in USB ports and outlets", "coordinates": {"lat": 40.6463, "lng": -73.7688, "floor": 2}},
        {"id": "amen_38", "name": "Charging Station - Terminal 8", "type": "charging", "terminal": "Terminal 8", "gate_area": "Near Gate 40", "description": "Mobile charging lockers and USB hubs", "coordinates": {"lat": 40.6483, "lng": -73.7623, "floor": 2}},
        {"id": "amen_39", "name": "Prayer Room - Terminal 1", "type": "prayer_room", "terminal": "Terminal 1", "gate_area": "Near Gate 5", "description": "Multi-faith prayer and meditation room", "coordinates": {"lat": 40.6458, "lng": -73.7808, "floor": 2}},
        {"id": "amen_40", "name": "Prayer Room - Terminal 4", "type": "prayer_room", "terminal": "Terminal 4", "gate_area": "Near B30", "description": "Multi-faith prayer and meditation room", "coordinates": {"lat": 40.6436, "lng": -73.7736, "floor": 3}},
        {"id": "amen_41", "name": "Prayer Room - Terminal 5", "type": "prayer_room", "terminal": "Terminal 5", "gate_area": "Near Gate 9", "description": "Multi-faith meditation and prayer space", "coordinates": {"lat": 40.6464, "lng": -73.7689, "floor": 2}},
        {"id": "amen_42", "name": "Prayer Room - Terminal 8", "type": "prayer_room", "terminal": "Terminal 8", "gate_area": "Near Gate 35", "description": "Multi-faith prayer and meditation room", "coordinates": {"lat": 40.6484, "lng": -73.7624, "floor": 2}},
        {"id": "amen_43", "name": "ATM - Terminal 1", "type": "atm", "terminal": "Terminal 1", "gate_area": "Near Entrance", "description": "24-hour ATM machine", "coordinates": {"lat": 40.6459, "lng": -73.7809, "floor": 1}},
        {"id": "amen_44", "name": "ATM - Terminal 4", "type": "atm", "terminal": "Terminal 4", "gate_area": "Near B20", "description": "24-hour ATM machine", "coordinates": {"lat": 40.6437, "lng": -73.7737, "floor": 2}},
        {"id": "amen_45", "name": "ATM - Terminal 5", "type": "atm", "terminal": "Terminal 5", "gate_area": "Near Baggage Claim", "description": "24-hour ATM machine", "coordinates": {"lat": 40.6465, "lng": -73.7690, "floor": 1}},
        {"id": "amen_46", "name": "ATM - Terminal 8", "type": "atm", "terminal": "Terminal 8", "gate_area": "Near Entrance", "description": "24-hour ATM machine", "coordinates": {"lat": 40.6485, "lng": -73.7625, "floor": 1}},
        {"id": "amen_47", "name": "Travelex Currency Exchange", "type": "pharmacy", "terminal": "Terminal 4", "gate_area": "Near B25", "description": "Currency exchange and pharmacy essentials", "coordinates": {"lat": 40.6438, "lng": -73.7738, "floor": 3}},
        {"id": "amen_48", "name": "Pharmacy - Terminal 4", "type": "pharmacy", "terminal": "Terminal 4", "gate_area": "Near B20", "description": "Pharmacy open 7 AM - 9 PM with over-the-counter medicines", "coordinates": {"lat": 40.6439, "lng": -73.7739, "floor": 2}},
        {"id": "amen_49", "name": "InMotion Tech", "type": "shop", "terminal": "Terminal 4", "gate_area": "Near B20", "description": "Tech accessories, cables, power banks, and headphones", "coordinates": {"lat": 40.6440, "lng": -73.7740, "floor": 2}},
        {"id": "amen_50", "name": "First Aid Station", "type": "medical", "terminal": "Terminal 4", "gate_area": "Near B28", "description": "Medical first aid station with trained personnel", "coordinates": {"lat": 40.6441, "lng": -73.7741, "floor": 2}},
    ],
    "parking": [
        {"id": "park_01", "name": "JFK Green Parking", "terminal": "All Terminals", "type": "economy", "capacity": 3800, "rates": {"hourly": None, "daily": 18, "weekly": 90}, "description": "Economy parking with free AirTrain shuttle"},
        {"id": "park_02", "name": "JFK Long-Term Parking", "terminal": "All Terminals", "type": "long_term", "capacity": 2500, "rates": {"hourly": None, "daily": 25, "weekly": 125}, "description": "Long-term covered parking with shuttle service"},
        {"id": "park_03", "name": "Terminal 1 Garage", "terminal": "Terminal 1", "type": "premium", "capacity": 1200, "rates": {"hourly": 8, "daily": 45, "weekly": 225}, "description": "Adjacent parking garage for Terminal 1"},
        {"id": "park_04", "name": "Terminal 4 Garage", "terminal": "Terminal 4", "type": "premium", "capacity": 1800, "rates": {"hourly": 8, "daily": 45, "weekly": 225}, "description": "Adjacent parking garage for Terminal 4"},
        {"id": "park_05", "name": "Terminal 5 Garage", "terminal": "Terminal 5", "type": "premium", "capacity": 1400, "rates": {"hourly": 8, "daily": 45, "weekly": 225}, "description": "Adjacent parking garage for Terminal 5"},
        {"id": "park_06", "name": "Terminal 8 Garage", "terminal": "Terminal 8", "type": "premium", "capacity": 1600, "rates": {"hourly": 8, "daily": 45, "weekly": 225}, "description": "Adjacent parking garage for Terminal 8"},
        {"id": "park_07", "name": "JFK Cell Phone Lot", "terminal": "All Terminals", "type": "waiting", "capacity": 500, "rates": {"hourly": 0, "daily": 0, "weekly": 0}, "description": "Free waiting area for picking up passengers"},
    ],
}
