# Generated by Django 5.2.16 on 2026-07-30 23:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('baggage', 'Baggage'), ('documents', 'Documents'), ('clothing', 'Clothing'), ('other', 'Other')], default='other', max_length=20)),
                ('location_found', models.CharField(blank=True, default='', max_length=255)),
                ('date_found', models.DateTimeField(auto_now_add=True)),
                ('photo_urls', models.JSONField(blank=True, default=list, null=True)),
                ('status', models.CharField(choices=[('unclaimed', 'Unclaimed'), ('matched', 'Matched'), ('returned', 'Returned')], default='unclaimed', max_length=20)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='found_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_found',),
            },
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('baggage', 'Baggage'), ('documents', 'Documents'), ('clothing', 'Clothing'), ('other', 'Other')], default='other', max_length=20)),
                ('location_found', models.CharField(blank=True, default='', max_length=255)),
                ('location_lost', models.CharField(blank=True, default='', max_length=255)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('matched', 'Matched'), ('closed', 'Closed')], default='open', max_length=20)),
                ('photo_urls', models.JSONField(blank=True, default=list, null=True)),
                ('qr_tracking_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('ai_classification', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
